source 'http://rubygems.org'

gem 'github-pages'
gem 'html-proofer'
gem 'jekyll-admin'
gem 'jekyll-seo-tag'
gem 'rake'
gem 'jekyll-gist'
gem 'jekyll-feed'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'webrick'